import type { SubtitleCue } from "./subtitles";

/**
 * 字幕导出：SRT / WebVTT / ASS（v1：默认样式 + 可选双语第二行）。
 * 纯函数，Node 可测。
 */

const pad = (value: number, width: number): string =>
  String(Math.floor(value)).padStart(width, "0");

/** SRT：HH:MM:SS,mmm */
export function srtTimestamp(seconds: number): string {
  const clamped = Math.max(0, seconds);
  const ms = Math.round((clamped - Math.floor(clamped)) * 1000);
  const whole = ms === 1000 ? Math.floor(clamped) + 1 : Math.floor(clamped);
  const millis = ms === 1000 ? 0 : ms;
  return `${pad(whole / 3600, 2)}:${pad((whole / 60) % 60, 2)}:${pad(whole % 60, 2)},${pad(millis, 3)}`;
}

/** WebVTT：HH:MM:SS.mmm */
export function vttTimestamp(seconds: number): string {
  return srtTimestamp(seconds).replace(",", ".");
}

/** ASS：H:MM:SS.cc（厘秒） */
export function assTimestamp(seconds: number): string {
  const clamped = Math.max(0, seconds);
  const cs = Math.round((clamped - Math.floor(clamped)) * 100);
  const whole = cs === 100 ? Math.floor(clamped) + 1 : Math.floor(clamped);
  const centis = cs === 100 ? 0 : cs;
  return `${Math.floor(whole / 3600)}:${pad((whole / 60) % 60, 2)}:${pad(whole % 60, 2)}.${pad(centis, 2)}`;
}

function cueText(cue: SubtitleCue, separator: string): string {
  const translation = cue.translation;
  return translation !== undefined && translation.length > 0
    ? `${cue.text}${separator}${translation}`
    : cue.text;
}

export function toSrt(cues: ReadonlyArray<SubtitleCue>): string {
  return (
    cues
      .map((cue, index) =>
        [
          String(index + 1),
          `${srtTimestamp(cue.start)} --> ${srtTimestamp(cue.end)}`,
          cueText(cue, "\n"),
        ].join("\n"),
      )
      .join("\n\n") + (cues.length > 0 ? "\n" : "")
  );
}

export function toVtt(cues: ReadonlyArray<SubtitleCue>): string {
  const body = cues
    .map((cue, index) =>
      [
        String(index + 1),
        `${vttTimestamp(cue.start)} --> ${vttTimestamp(cue.end)}`,
        cueText(cue, "\n"),
      ].join("\n"),
    )
    .join("\n\n");
  return `WEBVTT\n\n${body}${cues.length > 0 ? "\n" : ""}`;
}

const ASS_HEADER = (title: string): string =>
  [
    "[Script Info]",
    `; Generated by BCR Media Studio`,
    `Title: ${title}`,
    "ScriptType: v4.00+",
    "PlayResX: 1920",
    "PlayResY: 1080",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    "Style: Default,IBM Plex Sans,54,&H00FFFFFF,&H000000FF,&H00202020,&H80000000,0,0,0,0,100,100,0,0,1,2,1,2,80,80,60,1",
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ].join("\n");

export function toAss(cues: ReadonlyArray<SubtitleCue>, title = "BCR Subtitles"): string {
  const events = cues.map(
    (cue) =>
      `Dialogue: 0,${assTimestamp(cue.start)},${assTimestamp(cue.end)},Default,,0,0,0,,${cueText(cue, "\\N")}`,
  );
  return `${ASS_HEADER(title)}\n${events.join("\n")}\n`;
}

export type SubtitleFormat = "srt" | "vtt" | "ass";

export function exportSubtitles(
  cues: ReadonlyArray<SubtitleCue>,
  format: SubtitleFormat,
  title?: string,
): string {
  switch (format) {
    case "srt":
      return toSrt(cues);
    case "vtt":
      return toVtt(cues);
    case "ass":
      return toAss(cues, title);
  }
}

export const FORMAT_MIME: Record<SubtitleFormat, string> = {
  srt: "application/x-subrip",
  vtt: "text/vtt",
  ass: "text/x-ssa",
};
