export type {
  LocatorKind,
  ReaderBook,
  ReaderAnnotation,
  ReaderBookmark,
  ReaderFormat,
  ReaderLocator,
  ReaderProgress,
  ReaderSection,
  ReaderSectionKind,
  ReaderTocItem,
  ReaderSource,
  ReaderSourceRef,
  ReaderTextAnchor,
  SearchHit,
} from "./model";
export {
  READER_FORMAT_CATALOG,
  readerAcceptAttribute,
  readerFormatDescriptor,
  type ReaderFormatDescriptor,
  type ReaderFormatSupport,
} from "./formats";
export {
  clampProgression,
  createLocator,
  firstLocator,
  locatorAtPercentage,
  normalizeAnnotation,
  normalizeBookmark,
  normalizeLocator,
  normalizeTextAnchor,
  percentageForLocator,
  progressForLocator,
  createTextAnchor,
  createTextLocator,
  resolveTextAnchor,
  sameLocator,
  sectionReadingWeight,
} from "./locator";
export {
  buildSearchIndex,
  makeSnippet,
  normalizeSearchQuery,
  searchBook,
  searchIndexedDocuments,
  searchLibrary,
  searchTextRange,
  searchTextRanges,
  searchTextRangeNear,
  type ReaderIndexBook,
  type ReaderIndexDocument,
  type SearchTextRange,
} from "./search";
export { adapterFor, type ReaderAdapter, type ReaderOpenInput } from "./adapter";
