import type { MarketInstrument } from "./model";

export const PULSE_INSTRUMENTS: ReadonlyArray<MarketInstrument> = [
  {
    id: "CN:SSE:000001",
    symbol: "000001.SH",
    sourceSymbol: "sh000001",
    name: "Shanghai Composite",
    shortName: "SSE",
    market: "CN",
    venue: "Shanghai",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    assetClass: "index",
  },
  {
    id: "CN:SSE:000300",
    symbol: "000300.SH",
    sourceSymbol: "sh000300",
    name: "CSI 300",
    shortName: "CSI 300",
    market: "CN",
    venue: "Shanghai",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    assetClass: "index",
  },
  {
    id: "CN:SZSE:399006",
    symbol: "399006.SZ",
    sourceSymbol: "sz399006",
    name: "ChiNext Index",
    shortName: "CHINEXT",
    market: "CN",
    venue: "Shenzhen",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    assetClass: "index",
  },
  {
    id: "CN:SSE:600519",
    symbol: "600519.SH",
    sourceSymbol: "sh600519",
    name: "Kweichow Moutai",
    shortName: "MOUTAI",
    market: "CN",
    venue: "Shanghai",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    assetClass: "equity",
  },
  {
    id: "CN:SSE:600036",
    symbol: "600036.SH",
    sourceSymbol: "sh600036",
    name: "China Merchants Bank",
    shortName: "CMB",
    market: "CN",
    venue: "Shanghai",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    assetClass: "equity",
  },
  {
    id: "HK:HKEX:HSI",
    symbol: "HSI.HK",
    sourceSymbol: "HSI",
    name: "Hang Seng Index",
    shortName: "HANG SENG",
    market: "HK",
    venue: "Hong Kong",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    assetClass: "index",
  },
  {
    id: "HK:HKEX:HSTECH",
    symbol: "HSTECH.HK",
    sourceSymbol: "HSTECH",
    name: "Hang Seng TECH",
    shortName: "HS TECH",
    market: "HK",
    venue: "Hong Kong",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    assetClass: "index",
  },
  {
    id: "HK:HKEX:00700",
    symbol: "00700.HK",
    sourceSymbol: "00700",
    name: "Tencent Holdings",
    shortName: "TENCENT",
    market: "HK",
    venue: "Hong Kong",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    assetClass: "equity",
  },
  {
    id: "HK:HKEX:09988",
    symbol: "09988.HK",
    sourceSymbol: "09988",
    name: "Alibaba Group",
    shortName: "ALIBABA",
    market: "HK",
    venue: "Hong Kong",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    assetClass: "equity",
  },
  {
    id: "HK:HKEX:01810",
    symbol: "01810.HK",
    sourceSymbol: "01810",
    name: "Xiaomi Corporation",
    shortName: "XIAOMI",
    market: "HK",
    venue: "Hong Kong",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    assetClass: "equity",
  },
  {
    id: "US:INDEX:DJI",
    symbol: "DJI",
    sourceSymbol: "DJI",
    name: "Dow Jones Industrial",
    shortName: "DOW",
    market: "US",
    venue: "New York",
    currency: "USD",
    timezone: "America/New_York",
    assetClass: "index",
  },
  {
    id: "US:INDEX:INX",
    symbol: "INX",
    sourceSymbol: "INX",
    name: "S&P 500",
    shortName: "S&P 500",
    market: "US",
    venue: "New York",
    currency: "USD",
    timezone: "America/New_York",
    assetClass: "index",
  },
  {
    id: "US:INDEX:IXIC",
    symbol: "IXIC",
    sourceSymbol: "IXIC",
    name: "Nasdaq Composite",
    shortName: "NASDAQ",
    market: "US",
    venue: "New York",
    currency: "USD",
    timezone: "America/New_York",
    assetClass: "index",
  },
  {
    id: "US:NASDAQ:AAPL",
    symbol: "AAPL",
    sourceSymbol: "AAPL",
    name: "Apple",
    shortName: "APPLE",
    market: "US",
    venue: "Nasdaq",
    currency: "USD",
    timezone: "America/New_York",
    assetClass: "equity",
  },
  {
    id: "US:NASDAQ:NVDA",
    symbol: "NVDA",
    sourceSymbol: "NVDA",
    name: "NVIDIA",
    shortName: "NVIDIA",
    market: "US",
    venue: "Nasdaq",
    currency: "USD",
    timezone: "America/New_York",
    assetClass: "equity",
  },
];

export function instrumentsFor(market: "CN" | "HK" | "US"): ReadonlyArray<MarketInstrument> {
  return PULSE_INSTRUMENTS.filter((instrument) => instrument.market === market);
}
